jobs:
  - name: Mineur
    icon: DIAMOND_PICKAXE
    command-name: Miner
    description:
      - Gagnez de l'argent en minant.
      - Idéal pour les explorateurs souterrains.
  - name: Bûcheron
    icon: DIAMOND_AXE
    command-name: Woodcutter
    description:
      - Coupez du bois et développez les forêts.
      - Simple, stable et utile.
  - name: Pêcheur
    icon: FISHING_ROD
    command-name: Fisherman
    description:
      - Pêchez pour gagner de l'argent.
      - Calme et rentable.
  - name: Fermier
    icon: WHEAT
    command-name: Farmer
    description:
      - Cultivez, récoltez et nourrissez MoodCraft.
      - Parfait pour les joueurs paisibles.
  - name: Chasseur
    icon: BOW
    command-name: Hunter
    description:
      - Chassez les créatures hostiles.
      - Métier actif et dangereux.
  - name: Constructeur
    icon: BRICKS
    command-name: Builder
    description:
      - Construisez pour progresser.
      - Idéal pour les bâtisseurs.
settings:
  intercept-jobs-command: true
