jobs:
  - name: Mineur
    icon: GOLDEN_PICKAXE
    command-name: Mineur
    description:
      - Minerais, pierres et souterrains.
      - Métier simple pour commencer.
  - name: Bûcheron
    icon: DIAMOND_AXE
    command-name: Bucheron
    description:
      - Bois, troncs et forêts.
      - Métier utile pour les builders.
  - name: Agriculteur
    icon: WOODEN_HOE
    command-name: Fermier
    description:
      - Cultures, champs et récoltes.
      - Métier calme et régulier.
  - name: Chasseur
    icon: IRON_SWORD
    command-name: Chasseur
    description:
      - Animaux, monstres et combats.
      - Métier actif et risqué.
settings:
  intercept-jobs-command: true
