jobs:
  - name: Mineur
    icon: GOLDEN_PICKAXE
    command-name: Miner
    description:
      - Casse des minerais et blocs rares.
      - Charbon 1€ / Fer 2€ / Or 3€.
      - Diamant 12€ / Émeraude 15€.
      - Débris antiques 25€.
  - name: Bûcheron
    icon: DIAMOND_AXE
    command-name: Woodcutter
    description:
      - Coupe les arbres et tiges du Nether.
      - Bois classiques 2€.
      - Acacia 2.2€.
      - Mangrove, cerisier 3€.
      - Crimson, warped 4€.
  - name: Agriculteur
    icon: WOODEN_HOE
    command-name: Farmer
    description:
      - Cultive et récolte tes champs.
      - Blé, carottes, patates 1€.
      - Citrouille, melon, cacao 2€.
      - Miel et rayon de miel 3€.
  - name: Chasseur
    icon: IRON_SWORD
    command-name: Hunter
    description:
      - Tue animaux, monstres et boss.
      - Animaux 2€ à 4€.
      - Monstres 4€ à 60€.
      - Boss et rares 100€ à 450€.
settings:
  intercept-jobs-command: true
  normalize-default-jobs-reborn-names: true
